# Generated by Django 3.2.6 on 2021-08-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chat_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sender_id', models.IntegerField(unique=True)),
                ('receiver_id', models.IntegerField(unique=True)),
                ('last_message', models.CharField(blank=True, max_length=250)),
                ('message', models.CharField(max_length=350)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
