# Generated by Django 3.2.6 on 2021-08-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='last_message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
