# Generated by Django 3.2.6 on 2021-08-24 05:33

import APIs.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.FileField(blank=True, max_length=254, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/'), upload_to=APIs.models.user_dir),
        ),
    ]
